services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - ./src:/var/www/
    working_dir: /var/www
    depends_on:
      - db
      - redis
  web:
    build:
      context: ./
      dockerfile: ./.docker/web/Dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www/
      - ./.docker/web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: app
      POSTGRES_USER: app_user
  redis:
    image: redis